name: Build Server

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_WRAPPER_OUT_DIR: /srv/build

    strategy:
      fail-fast: false
      matrix:
        type: [debug, release]

    container:
      image: ghcr.io/zen0x7/compiler:1.89.0-${{ matrix.type }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check format
        run: |
          bash scripts/check-format.sh

      - name: Install Build Wrapper
        uses: SonarSource/sonarqube-scan-action/install-build-wrapper@fd88b7d7ccbaefd23d8f36f73b59db7a3d246602

      - name: Run Build Wrapper
        run: |
          build-wrapper-linux-x86-64 --out-dir ${{ env.BUILD_WRAPPER_OUT_DIR }} bash scripts/build.sh ${{ matrix.type }}

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@fd88b7d7ccbaefd23d8f36f73b59db7a3d246602
        if: matrix.type == 'debug'
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            --define "sonar.cfamily.compile-commands=${{ env.BUILD_WRAPPER_OUT_DIR }}/compile_commands.json"

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7
        if: matrix.type == 'debug'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}