name: Build Server

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_WRAPPER_OUT_DIR: /srv/build

    strategy:
      fail-fast: false
      matrix:
        version: [1.87, 1.88, 1.89]
        type: [debug, release]
        link: [shared, static]

    container:
      image: ghcr.io/zen0x7/compiler:${{ matrix.version }}.0-${{ matrix.link }}-${{ matrix.type }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Build Wrapper
        uses: SonarSource/sonarqube-scan-action/install-build-wrapper@fd88b7d7ccbaefd23d8f36f73b59db7a3d246602

      - name: Run Build Wrapper
        run: |
          build-wrapper-linux-x86-64 --out-dir ${{ env.BUILD_WRAPPER_OUT_DIR }} bash scripts/build.sh ${{ matrix.type }} ${{ matrix.link }}

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@fd88b7d7ccbaefd23d8f36f73b59db7a3d246602
        if: ${{ matrix.type == 'debug' && matrix.version == '1.89' && matrix.link == 'static' }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            --define "sonar.cfamily.compile-commands=${{ env.BUILD_WRAPPER_OUT_DIR }}/compile_commands.json"

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7
        if: ${{ matrix.type == 'debug' && matrix.version == '1.89' && matrix.link == 'static' }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}