name: Build Server

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_WRAPPER_OUT_DIR: /srv/build

    strategy:
      fail-fast: false
      matrix:
        version: [1.87, 1.88, 1.89]
        type: [debug, release]
        link: [shared, static]

    container:
      image: ghcr.io/zen0x7/compiler:${{ matrix.version }}.0-${{ matrix.type }}-${{ matrix.link }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check format
        run: |
          bash scripts/check-format.sh

      - name: Run Build Wrapper
        run: |
          sh scripts/build.sh ${{ matrix.type }} ${{ matrix.link }}

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7
        if: ${{ matrix.type == 'debug' && matrix.version == '1.89' && matrix.link == 'shared' }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}