name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        type: [debug, release]

    container:
      image: ghcr.io/zen0x7/compiler:1.89.0-${{ matrix.type }}

    steps:
      - uses: actions/checkout@v4

      - name: Check format
        run: |
          bash scripts/check-format.sh

      - name: Build and test
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.type }} -DENABLE_TESTS=ON
          make -j4
          ctest  --output-on-failure --verbose
          cd ..
          gcovr --filter='src/' --print-summary --sort=uncovered-percent --gcov-ignore-parse-errors=negative_hits.warn

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}